AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notion-database-putter

  SAM Template for notion-database-putter

Parameters:
  NotionApiToken:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  NotionDatabasePutterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: notion-database-putter-function
      CodeUri: putter/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        Putter:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /putter
            Method: post
      Environment:
        Variables:
          NOTION_API_TOKEN: !Ref NotionApiToken
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler/app.ts
  NotionDatabasePutterFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${NotionDatabasePutterFunction}
      RetentionInDays: 14

Outputs:
  NotionDatabasePutterApi:
    Description: "API Gateway endpoint URL for Prod stage for NotionDatabasePutterFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/putter/"

