AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notion-database-putter

  SAM Template for notion-database-putter

Parameters:
  NotionApiToken:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  StartFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: putter/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - arm64
      Events:
        Putter:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /putter
            Method: post
      Environment:
        Variables:
          START_FUNCTION_ARN: !GetAtt PutterFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref PutterFunction
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - functions/start/app.ts
  StartFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${StartFunction}
      RetentionInDays: 14

  PutterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: putter/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - arm64
      Environment:
        Variables:
          NOTION_API_TOKEN: !Ref NotionApiToken
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - functions/putter/app.ts
  PutterFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${PutterFunction}
      RetentionInDays: 14

Outputs:
  PutterStartApi:
    Description: "API Gateway endpoint URL for Prod stage for PutterFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/putter/"

